[package]
name = "weather_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = {version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
colored = "2.0"
thiserror = "2.0.9"
dotenvy = "0.15.7"
