[package]
name = "basic_web_scraper_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
tokio = { version = "1", features = ["full"] }
scraper = "0.22.0"
thiserror = "2.0.9"
url = "2.2.2"
robots_txt = "0.7.0"